### ISSUE TITLE
Transaction Identifier

### ISSUE THREAD

**Issue by ACarvalhaes** [stephan1827/modbusTCP-DotNET#6]
Good morning,

Am I not understanding the code the right way, or is the transaction identifier in the frame the master sends, the function code, and not a unique number that identifies the transaction?

Sorry for the trouble, and thank you very much for your help

**Comment by stephan1827** [comment]
The transaction ID is used to identify the request when you use asynchronous request. In this case you can send multiple request but you may not get them back in order. You can use the ID to identify the request in the call back function.
