### ISSUE TITLE
Continuous communication problem

### ISSUE THREAD

**Issue by NevzatBOL** [stephan1827/modbusTCP-DotNET#8]
I'm communicating with the plc using the library you shared. I have to constantly read and write data from plc. But when the connection is open for a long time, it breaks.

Readme says the following description;
Remember that a lot of Modbus clients use a watchdog telegram to make sure the master is still active. If you don’t call this watchdog within a specified time, the slave will close the connection. This feature is used to avoid unused open ports when the connection is interrupted.

How can I resolve the disconnection? 

Thank you for your sharing and support.

**Comment by stephan1827** [comment]
Hi, how long does the connection stay open? The watchdog I mentioned in the readme is typically a few seconds or minutes at the most. If the connection is interrupted you have to figure out what side is closing the connection. You could try a generic Windows modbus master and let the client run against that master. 

The function 

`private void MBmaster_OnException(ushort id, byte unit, byte function, byte exception)`

could give you more details what is going wrong.

**Comment by stephan1827** [comment]
No response
