### ISSUE TITLE
Hi Some Parallel For Issue

### ISSUE THREAD

**Issue by johnny071518** [stephan1827/modbusTCP-DotNET#9]
Dear stephan
I am from Taiwan. Thanks for this source code, It is very helpful for me to study C#.
By the way, I have some question after I use Threading.Task . Is it possible to do  Parallel.For to connect multi-IP to get register values.? I do not know how to design local variable. I hope you can give some suggestion.
Here is my code 

    public partial class Form1 : Form
    {
     bool Trigflag = false;  
     int[] stor = new int[1];

 private void timer1_Tick(object sender, EventArgs e)
{   
Parallel.For(0, IP.Length, (j, state) => 
   {                   MBmaster = new Master(IP[j], 502, true);
                        MBmaster.OnResponseData += new ModbusTCP.Master.ResponseData(MBmaster_OnResponseData);
                        MBmaster.OnException += new ModbusTCP.Master.ExceptionData(MBmaster_OnException);
                        MBmaster.ReadHoldingRegister(3, 0, 0, 100);
                       while(!TrigFlag)
                       {   
                         Console.Writeline("waiting for response");
                         Thread.Sleep(50);  
                         }
                        TrigFlag = false;
                                for (int ll = 0; ll < stor.Length; ll++)
                                { Console.Writeline(stor[ll]);}
  });
}
        private void MBmaster_OnResponseData(ushort ID, byte unit, byte function, byte[] values)
        {
            // ------------------------------------------------------------------
            // Seperate calling threads
            if (this.InvokeRequired)
            {
                this.BeginInvoke(new Master.ResponseData(MBmaster_OnResponseData), new object[] { ID, unit, function, values });
                data = values;
                ShowAs(null, null);
                Trigflag = true;
                return;
            }
        }
        private void ShowAs(object sender, System.EventArgs e)
        {
            bool[] bits = new bool[1];
            int[] word = new int[1];
            if (data.Length < 2) return;
            int length = data.Length / 2 + Convert.ToInt16(data.Length % 2 > 0);
            word = new int[length];
            for (int x = 0; x < length; x += 1)
            {
                word[x] = data[x * 2] * 256 + data[x * 2 + 1];
            }           
        }
                       stor =word;
}

This code can be use in for loop. But in the multi-Thread Parallel.For function, it exist local var and global var problem.
I do not know how to fix it, Can you give some suggestion?

**Comment by stephan1827** [comment]
Hi, I am not familiar with multi threading. If you want to connect to multiple devices I would just create more instances of the MBmaster. I think you could even use the same callback function for all instances. When you create a read or write request you specify an ID. This can be any number and helps you to identify the return values in the callback function.

In your code it also seems that you call the asynchronous function ReadHoldingRegister but then wait for the response. Keep in mind that you can also call the function synchrounsly. In that case you dont need the callback function but it will block your application until the response is there. See the help file for more details about synchronous and asynchronous calls.

Stephan

**Comment by johnny071518** [comment]
Hi Stephan 
Sorry to my late reply. I get you suggestion. Now, I can use parallel.for function with synchronous. Also I find out multi Thread might not good choice for my case. Thread its cost is more higher than MultiTread its advantages in this case. I learn so much, Thank you again.

Wen
